CONFIG_XIP=y
CONFIG_FLASH_BASE_ADDRESS=0x10000000
CONFIG_FLASH_SIZE=256
CONFIG_SRAM_BASE_ADDRESS=0x30000000
CONFIG_SRAM_SIZE=256
CONFIG_SOC_EARLY_RESET_HOOK=y
CONFIG_MAIN_STACK_SIZE=65536
CONFIG_STDOUT_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_BOOTARGS=y
CONFIG_DYNAMIC_BOOTARGS=y
CONFIG_BOOTARGS_ARGS_BUFFER_SIZE=16384
