#!/usr/bin/env python3
"""Generate stage-3 q=12289 twiddle constants directly in candidate mq.c files."""

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent
REF = ROOT / "ref" / "mq.c"
Q = 12289
R = pow(2, 32, Q)
RINV = pow(R, -1, Q)
QINV16 = pow(Q, -1, 1 << 16)
BEGIN = "/* BEGIN GENERATED M55 STAGE3 TWIDDLES */"
END = "/* END GENERATED M55 STAGE3 TWIDDLES */"


def read_table(source: str, name: str) -> list[int]:
    match = re.search(
        rf"const uint16_t\s+{name}\[\]\s*=\s*\{{(.*?)\}};",
        source,
        re.S,
    )
    if match is None:
        raise ValueError(f"table not found: {name}")
    body = re.sub(r"/\*.*?\*/", "", match.group(1), flags=re.S)
    values = [int(x) for x in re.findall(r"\b\d+\b", body)]
    if len(values) != 1024:
        raise ValueError(f"{name}: expected 1024 values, got {len(values)}")
    return values


def s16(x: int) -> int:
    x &= 0xFFFF
    return x - 0x10000 if x >= 0x8000 else x


def normal_root(x: int) -> int:
    return (x * RINV) % Q


def centered(x: int) -> int:
    return x if x <= Q // 2 else x - Q


def round_div(x: int, d: int) -> int:
    if x >= 0:
        return (x + d // 2) // d
    return -((-x + d // 2) // d)


def odd_rep(x: int) -> int:
    candidates = [x - Q, x, x + Q]
    candidates = [
        z for z in candidates if -32768 < z < 32768 and (z & 1) != 0
    ]
    return min(candidates, key=abs)


def mont3_pair(x: int) -> tuple[int, int]:
    w = normal_root(x)
    root = odd_rep((w * (1 << 15)) % Q)
    twist = s16(-root * QINV16)
    return root, twist


def barrett_pair(x: int) -> tuple[int, int]:
    root = centered(normal_root(x))
    # MVE has the scalar-vector VMLA form, but no matching scalar VMLS
    # accepted by GAS.  Negate the quotient approximation so that the
    # third instruction is data += quotient*q instead of data -= quotient*q.
    twist = -round_div(root * (1 << 15), Q)
    return root, twist


def format_table(name: str, values: list[int]) -> str:
    rows = []
    for i in range(0, len(values), 8):
        rows.append("\t" + ", ".join(f"{x:6d}" for x in values[i:i + 8]) + ",")
    return (
        "ALIGN32\n"
        f"const int16_t {name}[1024] = {{\n"
        + "\n".join(rows)
        + "\n};\n"
    )


def generated_block(kind: str, gm: list[int], igm: list[int]) -> str:
    if kind == "mont3":
        transform = mont3_pair
        prefix = "fndsa_mq_mont3"
        description = "16-bit three-instruction rounding-Montgomery"
    elif kind == "barrett3":
        transform = barrett_pair
        prefix = "fndsa_mq_barrett3"
        description = "16-bit three-instruction known-twiddle Barrett"
    else:
        raise ValueError(kind)
    gm_pairs = [transform(x) for x in gm]
    igm_pairs = [transform(x) for x in igm]
    parts = [
        BEGIN,
        "/*",
        f" * q=12289 {description} constants.",
        " * The root and twist arrays have identical indices to mq_GM/mq_iGM.",
        " * Generated by generate_stage3_tables.py; do not edit by hand.",
        " */",
        format_table(f"{prefix}_GM", [x[0] for x in gm_pairs]).rstrip(),
        format_table(f"{prefix}_GM_twist", [x[1] for x in gm_pairs]).rstrip(),
        format_table(f"{prefix}_iGM", [x[0] for x in igm_pairs]).rstrip(),
        format_table(f"{prefix}_iGM_twist", [x[1] for x in igm_pairs]).rstrip(),
        END,
        "",
    ]
    return "\n".join(parts)


def update(path: Path, block: str) -> None:
    source = path.read_text()
    if BEGIN in source:
        source = source[:source.index(BEGIN)].rstrip() + "\n\n"
    path.write_text(source + block)


def main() -> None:
    source = REF.read_text()
    gm = read_table(source, "mq_GM")
    igm = read_table(source, "mq_iGM")
    update(
        ROOT / "m1_3instruction_montgomery" / "mq.c",
        generated_block("mont3", gm, igm),
    )
    update(
        ROOT / "b1_3instruction_Barrett" / "mq.c",
        generated_block("barrett3", gm, igm),
    )


if __name__ == "__main__":
    main()
