/* Host-only deterministic PUBLIC TEST keys; never deploy these secrets. */
#include "fndsa.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
static uint8_t sk[FNDSA_SIGN_KEY_SIZE(10)],pk[FNDSA_VRFY_KEY_SIZE(10)],tmp[22*1024+31];
int main(int argc,char **argv) {
 if(argc!=2)return 1;FILE *f=fopen(argv[1],"w");if(!f)return 2;
 fprintf(f,"/* Deterministic public test keys, generated by fn-dsa_ref. */\n");
 for(unsigned logn=9;logn<=10;logn++) {
  uint8_t seed[32];for(unsigned j=0;j<32;j++)seed[j]=(uint8_t)(7*j+logn);
  if(!fndsa_keygen_seeded_temp(logn,seed,32,sk,pk,tmp,sizeof tmp))return 3;
  for(unsigned which=0;which<2;which++) {
   const uint8_t *b=which?pk:sk;size_t len=which?FNDSA_VRFY_KEY_SIZE(logn):FNDSA_SIGN_KEY_SIZE(logn);
   fprintf(f,"static const uint8_t test_%s%u[%zu]={\n",which?"pk":"sk",1u<<logn,len);
   for(size_t j=0;j<len;j++)fprintf(f,"0x%02x,%s",b[j],j%16==15?"\n":"");
   fprintf(f,"\n};\n");
  }
 }
 return fclose(f)!=0;
}
