#!/usr/bin/env python3
"""Extract the immutable Q32 GM table from the local c-fn-dsa source."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT.parent / "fft_keygen" / "kgen_fxp.c"
OUT = ROOT / "reference" / "gm_q32.c"

text = SRC.read_text()
start = text.index("static const fxc GM_TAB[1024]")
end = text.index("};", start)
pairs = re.findall(r"FXC\(\s*([0-9]+)ull,\s*([0-9]+)ull\s*\)", text[start:end])
if len(pairs) != 1024:
    raise SystemExit(f"expected 1024 roots, got {len(pairs)}")
lines = [
    "/* Generated by tools/extract_gm.py; do not edit. */",
    '#include "api.h"',
    "const uint64_t tw_gm_q32[1024][2] = {",
]
lines += [f"\t{{ UINT64_C({a}), UINT64_C({b}) }}," for a, b in pairs]
lines += ["};", ""]
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(lines))
print(OUT)
